---
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3-node-browsers
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
  test:
    docker:
      - image: circleci/ruby:2.7.3-node-browsers
      - environment:
          POSTGRES_DB: dinshaw_cvZtest
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: circleci
        image: "circleci/postgres:9.5-alpine"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: "127.0.0.1"
      PGPASSWORD: ""
      PGUSER: circleci
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: "dockerize -wait tcp://localhost:5432 -timeout 1m"
          name: "Wait for DB"
      - run:
          command: "bundle exec rails db:schema:load --trace"
          name: "Database setup"
      - run:
          command: "bin/rails test:system test"
          name: "run ruby tests"
          when: always
      - store_test_results:
          path: test-results
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
      - run:
          command: |
            heroku run rails db:migrate -a dinshaw-cv
            heroku restart -a dinshaw-cv
          name: "Heroku post-deploy steps"
orbs:
  heroku: circleci/heroku@0.0.10
  node: circleci/node@3.0.1
  ruby: circleci/ruby@1.0.7
  browser-tools: circleci/browser-tools@1.0.1

version: 2.1

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
