development:
  host: localhost
  adapter: postgresql
  database: dinshaw-cv_development
  username: <%= `whoami` %>

test:
  host: localhost
  adapter: postgresql
  database: dinshaw-cv_test
  username: <%= `whoami` %>

production:
  host: localhost
  adapter: postgresql
  database: dinshaw-cv_prod
  username: <%= `whoami` %>
