development:
  encoding: utf8
  adapter: postgresql
  database: dinshaw_cv_dev
  username: <%= `whoami` %>

test:
  encoding: utf8
  pool: 10
  adapter: postgresql
  database: dinshaw_cv_test
  username: <%= `whoami` %>
